/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;
import java.util.Scanner;

public class App {
 
    public void promocao(Produto prod){
        
    System.out.println("O produto " + prod.getName()+ " está em promoção por apenas "+ prod.getPreco());    
    }

    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
        int numero1, numero2;
        
        System.out.println("Digite um número: ");
        numero1=sc.nextInt(); //nextLine para string
        
        System.out.println("Digite outro número: ");
        numero2=sc.nextInt();
        
        System.out.println("Resultado: "+ numero1 + "e " + numero2);
        
        
        
        
        /*
        teste meuTeste = new teste();
        meuTeste.somar(9, 111);
        */
        /*
        int idade = 30;//INT para números inteiros
        double altura = 1.70; // DOUBLE para números que podem ter casas decimais
        String nome = "Luut";// STRING com S Maiúsculo para letras
        char inicial= 'L'; //CHAR para um único caracter sempre com aspas simples
        boolean souEstudante = true; //BOOLEAN para verdadeiro ou falso


        
        int numero = 0;
        if(numero>0){
            System.out.println("o número é positivo");
        }else if (numero ==0){
         System.out.println("o número é igual a zero");
        }        
        else{
            System.out.println("o número é negativo");
        }
   }
*/
        /*
        int diasDaSemana=0;
        
        switch (diasDaSemana){
            case 1:
                System.out.println("Domingo");
                break;
            case 2:
                System.out.println("Segunda");
                break;
            case 3:
                System.out.println("Terça");
                break;
            case 4:
                System.out.println("Quarta");
                break;
            case 5:
                System.out.println("Quinta");
                break;
            case 6:
                System.out.println("Sexta");
                break;
            case 7:
                System.out.println("Sabado");
                break;
            default:
                System.out.println("Não existe esse dia na semana");
                break;
        }
        
    int voltas = 0;
    
    while (voltas<10){
    System.out.println("pedale, você já deu" +voltas+"voltas");
    voltas++;
    }
    
    System.out.println("você chegou ao final");
    */
        
     Pessoa novaPessoa=new Pessoa("Luut",30);
     novaPessoa.caminhar();
    
    System.out.println(novaPessoa.nome);
    
    Produto novoProd=new Produto("Café", 19.99);
    
    System.out.println(novoProd.getName());
    
    Eletronico novoElet = new Eletronico("TV", 199.99,220);
    
    System.out.println(novoElet.getTensao());
    
    App meuApp=new App();
    meuApp.promocao(novoElet);
            
            
    
    
    
    }
    
}
