/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio1;
import java.util.Scanner;

public class App {
  

    public static void main(String[] args) {
        
        Calculadora calc=new Calculadora();
        
            // Cria um objeto Scanner para ler a entrada do usuário
        Scanner sc = new Scanner(System.in);

        // Declara duas variáveis inteiras para armazenar os números digitados pelo usuário
        int numero1, numero2, numero3;

        // Solicita ao usuário que digite o primeiro número
        System.out.println("Digite um número: ");
        numero1 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero1

        // Solicita ao usuário que digite o segundo número
        System.out.println("Digite outro número: ");
        numero2 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero2

                
        
         System.out.println("Qual operacao deseja realizar?\n[1]-Soma\n[2]-Subtracao\n[3]-Divisao\n[4]-Multiplicacao");
        numero3 = sc.nextInt();
        
        
        
        switch(numero3){
            
            case 1: 
                  System.out.println("O resultado da soma de "+numero1+" + "+numero2+" e: "+calc.soma(numero1,numero2));
                break;
            case 2: 
                System.out.println("O resultado da subtracao de "+numero1+" - "+numero2+" e: "+calc.sub(numero1,numero2));
                break;
            case 3:                
                if(numero1==0||numero2==0){
                System.out.println("Não é possível divisão por ZERO");
                }else{
                System.out.println("O resultado da divisao de "+numero1+" por "+numero2+" e: "+calc.div( numero1,numero2));
                 }
                break;
            case 4: 
                System.out.println("O resultado da multiplicacao de "+numero1+" por "+numero2+" e: "+calc.mult(numero1,numero2));
                break;
                default:  System.out.println("Escolha inválida");
               
        }        
    }
}
