/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuSegundoProjetoJAVA;
// Importa a classe Scanner para permitir a entrada de dados do usuário
import java.util.Scanner;


public class App {
   
    public static void main(String[] args) {
        
        // Cria um objeto Scanner para ler a entrada do usuário
        Scanner sc = new Scanner(System.in);
        
        // Declara duas variáveis inteiras para armazenar os números digitados pelo usuário
        int numero1, numero2;
        String nome;
        
         System.out.println("Digite um nome: ");
        nome = sc.nextLine();
        
        // Solicita ao usuário que digite o primeiro número
        System.out.println("Digite um número: ");
        numero1 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero1
        
        // Solicita ao usuário que digite o segundo número
        System.out.println("Digite outro número: ");
        numero2 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero2
        
        // Exibe uma mensagem para indicar que o resultado será mostrado
        System.out.println("Resultado: " + (numero1 + numero2));
        
        
        
      /* 
        Frase minhaFrase=new Frase();
    minhaFrase.imprimeFrase();
    
    
    
    Veiculo fordFocus=new Veiculo(4,"Ford",349.899);
    fordFocus.andar();
    
    Carro chevette=new Carro ("Chevrolet", 1300, 2);
    
    
      chevette.cavalinhoDePau();
      chevette.andar();
    
    */
    
    
    }
}
